# Generated by Django 6.0.2 on 2026-03-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0002_add_tenant_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenantcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tenantcontact',
            name='timezone',
        ),
    ]
