# Generated by Django 6.0.2 on 2026-02-27 20:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('host', 'Host'), ('webapp', 'WebApp'), ('api', 'API'), ('cloud', 'Cloud'), ('network_device', 'Network Device'), ('mobile_app', 'Mobile App'), ('other', 'Other')], default='host', max_length=32)),
                ('environment', models.CharField(choices=[('prod', 'Prod'), ('staging', 'Staging'), ('dev', 'Dev'), ('lab', 'Lab')], default='prod', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('target', models.CharField(blank=True, default='', max_length=220)),
                ('notes', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
