# Generated by Django 6.0.2 on 2026-02-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('clients', '0001_initial'),
        ('tenancy', '0004_collapse_roles_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='clients.client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'asset_type'], name='assets_asse_tenant__0cec78_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'client'], name='assets_asse_tenant__3b6110_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', '-created_at'], name='assets_asse_tenant__ae80f8_idx'),
        ),
    ]
