# Generated by Django 6.0.2 on 2026-03-10 13:44

from django.db import migrations


def seed_free_plan(apps, schema_editor):
    """Create the Free plan and assign it to all existing tenants."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    TenantSubscription = apps.get_model('subscriptions', 'TenantSubscription')
    Tenant = apps.get_model('tenancy', 'Tenant')

    plan, _ = SubscriptionPlan.objects.get_or_create(
        code='free',
        defaults={
            'name': 'Free',
            'description': 'Free plan with basic limits.',
            'is_default': True,
            'is_active': True,
            'display_order': 0,
            'max_members': 3,
            'max_clients': 5,
            'max_assets': 10,
            'max_engagements': 5,
            'max_findings_per_engagement': 20,
            'max_images_per_finding': 5,
            'audit_log_enabled': True,
            'data_export_enabled': False,
            'custom_branding_enabled': False,
        },
    )

    # Backfill: assign to all existing tenants that don't have a subscription
    for tenant in Tenant.objects.filter(status='active'):
        TenantSubscription.objects.get_or_create(
            tenant=tenant,
            defaults={
                'plan': plan,
                'status': 'active',
            },
        )


def reverse_seed(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    TenantSubscription = apps.get_model('subscriptions', 'TenantSubscription')
    TenantSubscription.objects.filter(plan__code='free').delete()
    SubscriptionPlan.objects.filter(code='free').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_free_plan, reverse_seed),
    ]
