# Generated by Django 6.0.2 on 2026-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_free_plan_max_engagements_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_projects',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
