# Generated by Django 6.0.2 on 2026-02-28 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0003_sowasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('orphaned', 'Orphaned')], default='draft', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_uri', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
