# Generated by Django 6.0.2 on 2026-02-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('findings', '0001_initial'),
        ('tenancy', '0004_collapse_roles_enum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inline_attachments', to='findings.finding'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'sha256'], name='evidence_at_tenant__f1c4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', '-created_at'], name='evidence_at_tenant__1d7187_idx'),
        ),
    ]
