# Generated by Django 6.0.2 on 2026-04-12 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_engagement_type'),
        ('evidence', '0003_malware_sample'),
        ('tenancy', '0008_tenantclosure_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('disk_image', 'Disk Image'), ('memory_dump', 'Memory Dump'), ('network_capture', 'Network Capture'), ('log_file', 'Log File'), ('mobile_extraction', 'Mobile Extraction'), ('other', 'Other')], default='other', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('chain_of_custody', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_sources_created', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='engagements.engagement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'engagement'], name='evidence_ev_tenant__50aa39_idx')],
            },
        ),
    ]
