# Generated by Django 6.0.2 on 2026-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_evidencesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesource',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('live', 'Live Acquisition'), ('dead', 'Dead / Offline'), ('network_tap', 'Network Tap'), ('manual_export', 'Manual Export'), ('other', 'Other')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='evidencesource',
            name='acquisition_tool',
            field=models.CharField(blank=True, default='', help_text='Tool used for acquisition (e.g. FTK Imager, Volatility).', max_length=255),
        ),
        migrations.AddField(
            model_name='evidencesource',
            name='source_device',
            field=models.CharField(blank=True, default='', help_text='Source device identifier (hostname, serial, asset tag).', max_length=255),
        ),
        migrations.AddField(
            model_name='evidencesource',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='File path or URI where the evidence is stored.', max_length=1024),
        ),
    ]
