# Generated by Django 6.0.2 on 2026-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_uri',
            field=models.TextField(blank=True, default=''),
        ),
    ]
