# Generated by Django 6.0.2 on 2026-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_mfa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_totp_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
