# Generated by Django 6.0.2 on 2026-03-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
