# Generated by Django 6.0.2 on 2026-03-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_last_password_reset_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_password_reset_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_verification_sent_at',
        ),
    ]
