# Generated by Django 6.0.2 on 2026-03-13 04:53

from django.db import migrations


def seed_comment_permissions(apps, schema_editor):
    Permission = apps.get_model("authorization", "Permission")
    TenantGroup = apps.get_model("authorization", "TenantGroup")

    perms_data = [
        ("comment.create", "Create comments", "model", "comment"),
        ("comment.edit", "Edit comments", "model", "comment"),
        ("comment.delete", "Delete any comment", "model", "comment"),
    ]

    perm_objs = []
    for codename, name, category, resource in perms_data:
        obj, _ = Permission.objects.update_or_create(
            codename=codename,
            defaults={"name": name, "category": category, "resource": resource},
        )
        perm_objs.append(obj)

    # Add to PenTesters (all 3) and Viewers (create only) for all tenants
    for group in TenantGroup.objects.filter(name="PenTesters", is_default=True):
        group.permissions.add(*perm_objs)

    # Viewers can create and edit their own comments
    create_perm = Permission.objects.get(codename="comment.create")
    edit_perm = Permission.objects.get(codename="comment.edit")
    for group in TenantGroup.objects.filter(name="Viewers", is_default=True):
        group.permissions.add(create_perm, edit_perm)

    # Admins get __all__ which includes these already via seed_permissions()
    for group in TenantGroup.objects.filter(name="Administrators", is_default=True):
        group.permissions.add(*perm_objs)


def reverse_seed(apps, schema_editor):
    Permission = apps.get_model("authorization", "Permission")
    Permission.objects.filter(codename__startswith="comment.").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_seed_tenant_close_permission"),
    ]

    operations = [
        migrations.RunPython(seed_comment_permissions, reverse_seed),
    ]
