# Generated by Django 6.0.2 on 2026-02-28 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('engagements', '0003_sowasset'),
        ('tenancy', '0004_collapse_roles_enum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triage', 'Triage'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('false_positive', 'False Positive')], default='open', max_length=24)),
                ('description_md', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_created', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='engagements.engagement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'severity'], name='findings_fi_tenant__223c1b_idx'), models.Index(fields=['tenant', 'status'], name='findings_fi_tenant__d088cd_idx'), models.Index(fields=['tenant', '-created_at'], name='findings_fi_tenant__ccd6db_idx')],
            },
        ),
    ]
