# Generated by Django 6.0.2 on 2026-02-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='recommendation_md',
            field=models.TextField(blank=True, default=''),
        ),
    ]
