# Generated by Django 6.0.2 on 2026-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_finding_recommendation_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
