# Generated by Django 6.0.2 on 2026-03-10 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('engagements', '0005_alter_sow_status'),
        ('findings', '0003_add_finding_is_draft'),
        ('tenancy', '0006_tenant_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename category → assessment_area (preserves existing data)
        migrations.RenameField(
            model_name='finding',
            old_name='category',
            new_name='assessment_area',
        ),
        # Alter the renamed field to apply new max_length and choices
        migrations.AlterField(
            model_name='finding',
            name='assessment_area',
            field=models.CharField(
                blank=True,
                choices=[
                    ('application_security', 'Application Security'),
                    ('network_security', 'Network Security'),
                    ('api_security', 'API Security'),
                    ('cloud_security', 'Cloud Security'),
                    ('infrastructure_security', 'Infrastructure Security'),
                    ('cryptography', 'Cryptography'),
                    ('auth_and_access_control', 'Authentication & Access Control'),
                    ('configuration_and_deployment', 'Configuration & Deployment'),
                    ('mobile_security', 'Mobile Security'),
                    ('social_engineering', 'Social Engineering'),
                    ('physical_security', 'Physical Security'),
                    ('compliance', 'Compliance'),
                ],
                default='',
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='cwe_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='owasp_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A01:2021', 'A01:2021 Broken Access Control'),
                    ('A02:2021', 'A02:2021 Cryptographic Failures'),
                    ('A03:2021', 'A03:2021 Injection'),
                    ('A04:2021', 'A04:2021 Insecure Design'),
                    ('A05:2021', 'A05:2021 Security Misconfiguration'),
                    ('A06:2021', 'A06:2021 Vulnerable and Outdated Components'),
                    ('A07:2021', 'A07:2021 Identification and Authentication Failures'),
                    ('A08:2021', 'A08:2021 Software and Data Integrity Failures'),
                    ('A09:2021', 'A09:2021 Security Logging and Monitoring Failures'),
                    ('A10:2021', 'A10:2021 Server-Side Request Forgery'),
                ],
                default='',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(
                fields=['tenant', 'assessment_area'],
                name='findings_fi_tenant__b72ebe_idx',
            ),
        ),
    ]
