# Generated by Django 6.0.2 on 2026-03-10 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_remove_finding_category_finding_assessment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='assessment_area',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='finding',
            name='owasp_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassificationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('assessment_area', 'Assessment Area'), ('owasp', 'OWASP Top 10'), ('cwe', 'CWE')], max_length=20)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['entry_type', 'code'],
                'indexes': [models.Index(fields=['entry_type'], name='findings_cl_entry_t_145732_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry_type', 'code'), name='unique_classification_entry')],
            },
        ),
    ]
