# Generated by Django 6.0.2 on 2026-03-31 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_malware_sample'),
        ('findings', '0007_seed_all_cwes'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='evidence.malwaresample'),
        ),
    ]
