# Generated by Django 6.0.2 on 2026-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0008_finding_sample_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('static', 'Static Analysis'), ('dynamic', 'Dynamic Analysis')], default='', max_length=16),
        ),
    ]
