# Generated by Django 6.0.2 on 2026-03-31 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('engagements', '0006_engagement_type'),
        ('evidence', '0003_malware_sample'),
        ('findings', '0009_finding_analysis_type'),
        ('tenancy', '0008_tenantclosure_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='analysis_check_key',
            field=models.CharField(blank=True, default='', help_text='Links to an analysis check definition. Empty for manual findings.', max_length=60),
        ),
        migrations.AddField(
            model_name='finding',
            name='execution_status',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='', help_text='Execution lifecycle for analysis check findings. Empty for manual findings.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['tenant', 'engagement', 'analysis_check_key'], name='findings_fi_tenant__447789_idx'),
        ),
    ]
