# Generated by Django 6.0.2 on 2026-04-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_evidencesource'),
        ('findings', '0010_finding_analysis_check_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='evidence_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='evidence.evidencesource'),
        ),
        migrations.AddField(
            model_name='finding',
            name='ioc_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='finding',
            name='ioc_value',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='finding',
            name='mitre_tactic',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='finding',
            name='mitre_technique',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
