# Generated by Django 6.0.2 on 2026-02-28 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sow', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
