# Generated by Django 6.0.2 on 2026-02-28 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('engagements', '0002_sow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SowAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_scope', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sow_links', to='assets.asset')),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sow_assets', to='engagements.sow')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('sow', 'asset'), name='uq_sow_asset_pair')],
            },
        ),
    ]
