# Generated by Django 6.0.2 on 2026-03-05 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_sowasset'),
        ('tenancy', '0004_collapse_roles_enum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_settings', to='engagements.engagement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('engagement', 'key'), name='unique_engagement_setting_key')],
            },
        ),
        migrations.CreateModel(
            name='EngagementStakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('account_manager', 'Account Manager'), ('project_manager', 'Project Manager'), ('security_engineer', 'Security Engineer'), ('lead_tester', 'Lead Tester'), ('qa_reviewer', 'QA Reviewer'), ('client_poc', 'Client Point of Contact'), ('technical_lead', 'Technical Lead'), ('observer', 'Observer')], default='account_manager', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='engagements.engagement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_entries', to='tenancy.tenantmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('engagement', 'member'), name='unique_engagement_stakeholder_member')],
            },
        ),
    ]
