# Generated by Django 6.0.2 on 2026-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_engagement_stakeholders_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
