# Generated by Django 6.0.2 on 2026-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0005_alter_sow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('web_app_pentest', 'Web App Pen Testing'), ('external_pentest', 'External Pen Testing'), ('mobile_pentest', 'Mobile Pen Testing'), ('internal_pentest', 'Internal Pen Testing'), ('wifi', 'WiFi Assessment'), ('malware_analysis', 'Malware Analysis'), ('digital_forensics', 'Digital Forensics'), ('active_directory', 'Active Directory'), ('linux_audit', 'Linux Server Audit'), ('windows_audit', 'Windows Audit'), ('general', 'General / Other')], default='general', max_length=30),
        ),
    ]
