# Generated by Django 6.0.2 on 2026-04-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_engagement_type'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='projects.project'),
        ),
    ]
