# Generated by Django 6.0.2 on 2026-02-27 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_collapse_roles_enum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'name'], name='clients_cli_tenant__157b19_idx'), models.Index(fields=['tenant', 'status'], name='clients_cli_tenant__11a885_idx')],
            },
        ),
    ]
