"""License key validation — validates signed JWT license keys.

The public key is embedded in the product. License keys are signed JWTs
generated by the BytesCop portal using the corresponding private key.

License key resolution order:
    1. AccountSetting with key='license_key' for the current tenant (DB)
    2. BC_LICENSE_KEY environment variable (fallback)

Usage:
    from licensing.service import get_license, has_feature

    license = get_license()
    if license and 'rbac' in license.features:
        # enterprise feature enabled
        ...

    # Or use the shortcut:
    if has_feature('rbac'):
        ...
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from django.conf import settings

logger = logging.getLogger('bytescop.licensing')

# Public key for verifying license signatures.
# Embedded in the product — cannot be used to forge licenses.
PUBLIC_KEY_PATH = Path(__file__).parent / 'public_key.pem'

COMMUNITY = 'community'


@dataclass
class License:
    customer: str = ''
    email: str = ''
    plan: str = COMMUNITY
    features: list[str] = field(default_factory=list)
    max_users: int = 0
    max_workspaces: int = 1
    issued_at: str = ''
    expires_at: str = ''
    valid: bool = False
    expired: bool = False

    @property
    def is_enterprise(self) -> bool:
        return self.plan in ('pro', 'enterprise') and self.valid and not self.expired


# Singleton cache
_license: License | None = None


def get_license(tenant=None) -> License:
    """Return the current license (cached). Returns a Community license if
    no key is configured or the key is invalid.

    If tenant is provided, checks DB for a tenant-scoped license key first.
    """
    global _license
    if _license is not None:
        return _license

    _license = _load_license(tenant=tenant)
    return _license


def reset_license() -> None:
    """Clear cached license (e.g., after key update)."""
    global _license
    _license = None


def has_feature(feature: str) -> bool:
    """Check if a feature is enabled by the current license."""
    lic = get_license()
    return feature in lic.features


def validate_license_key(key_str: str) -> License:
    """Validate a license key string and return the resulting License.

    Unlike _load_license(), this does NOT cache the result or read from DB/env.
    Use this for pre-validation before storing a key.

    Returns a License with valid=False if the key is invalid or unverifiable.
    """
    return _decode_key(key_str)


def _get_key_from_db(tenant) -> str:
    """Read license key from AccountSetting for the given tenant."""
    if tenant is None:
        return ''
    try:
        from account_settings.models import AccountSetting
        setting = AccountSetting.objects.filter(
            tenant=tenant,
            key='license_key',
        ).first()
        return setting.value if setting else ''
    except Exception:
        logger.debug('Could not read license key from DB', exc_info=True)
        return ''


def _load_license(tenant=None) -> License:
    """Load and validate the license key.

    Resolution order: DB (tenant-scoped) → env var → Community Edition.
    """
    # 1. Check DB first
    key_str = _get_key_from_db(tenant)

    # 2. Fall back to env var
    if not key_str.strip():
        key_str = getattr(settings, 'BC_LICENSE_KEY', '') or ''

    if not key_str.strip():
        logger.info('No license key configured — running as Community Edition')
        return License(plan=COMMUNITY, valid=True)

    return _decode_key(key_str)


def _decode_key(key_str: str) -> License:
    """Decode and validate a JWT license key string."""
    if not key_str or not key_str.strip():
        return License(plan=COMMUNITY, valid=True)

    try:
        import jwt

        if not PUBLIC_KEY_PATH.exists():
            logger.warning('License public key not found at %s', PUBLIC_KEY_PATH)
            return License(plan=COMMUNITY, valid=False)

        public_key = PUBLIC_KEY_PATH.read_text()

        payload = jwt.decode(
            key_str.strip(),
            public_key,
            algorithms=['RS256'],
            options={'verify_exp': False},  # we check expiry ourselves
        )

        # Check expiry
        expires_at = payload.get('expires_at', '')
        expired = False
        if expires_at:
            try:
                exp_dt = datetime.fromisoformat(expires_at)
                if exp_dt.tzinfo is None:
                    exp_dt = exp_dt.replace(tzinfo=timezone.utc)
                expired = exp_dt < datetime.now(timezone.utc)
            except (ValueError, TypeError):
                expired = True

        lic = License(
            customer=payload.get('customer', ''),
            email=payload.get('email', ''),
            plan=payload.get('plan', COMMUNITY),
            features=payload.get('features', []),
            max_users=payload.get('max_users', 0),
            max_workspaces=payload.get('max_workspaces', 1),
            issued_at=payload.get('issued_at', ''),
            expires_at=expires_at,
            valid=True,
            expired=expired,
        )

        if expired:
            logger.warning(
                'License expired on %s — features downgraded to Community Edition',
                expires_at,
            )
        else:
            logger.info(
                'License validated: customer=%s plan=%s features=%s expires=%s',
                lic.customer, lic.plan, lic.features, lic.expires_at,
            )

        return lic

    except Exception:
        logger.exception('Failed to validate license key')
        return License(plan=COMMUNITY, valid=False)
