# Generated by Django 6.0.2 on 2026-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmember',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='authorization.tenantgroup'),
        ),
    ]
