# Generated by Django 6.0.2 on 2026-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_collapse_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
