# Generated by Django 6.0.2 on 2026-03-06 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_collapse_roles_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmember',
            name='invite_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantmember',
            name='last_invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='tenancy.tenantmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
