# Generated by Django 6.0.2 on 2026-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_invite_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantClosure',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_slug', models.SlugField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('data_export_choice', models.CharField(choices=[('exported', 'I have exported and saved my data'), ('not_needed', "I don't need my data")], max_length=20)),
                ('last_export_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_code_hash', models.CharField(max_length=128)),
                ('code_expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_export_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('closing', 'Closing')], default='active', max_length=20),
        ),
    ]
