# Generated by Django 6.0.2 on 2026-03-01 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_collapse_roles_enum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(default='', max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('signup', 'Signup'), ('tenant_switch', 'Tenant Switch')], max_length=24)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('resource_repr', models.CharField(blank=True, default='', max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_path', models.CharField(blank=True, default='', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='audit_tenant_ts'), models.Index(fields=['tenant', 'action'], name='audit_tenant_action'), models.Index(fields=['tenant', 'resource_type'], name='audit_tenant_restype'), models.Index(fields=['tenant', 'actor'], name='audit_tenant_actor'), models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='audit_tenant_res')],
            },
        ),
    ]
