# Generated by Django 6.0.2 on 2026-03-13 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0006_tenant_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('engagement', 'Engagement'), ('finding', 'Finding')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('body_md', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'target_type', 'target_id'], name='comment_tenant_target'), models.Index(fields=['parent'], name='comment_parent')],
            },
        ),
    ]
