import uuid

from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings

from accounts.models import User
from evidence.models import Attachment
from evidence.services.attachment_upload import AttachmentUploadService
from evidence.signing import sign_attachment_url
from engagements.models import Engagement
from clients.models import Client
from tenancy.models import Tenant

# Valid 1x1 red PNG (generated by Pillow)
TINY_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01"
    b"\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00"
    b"\x00\x00\x0cIDATx\x9cc\xf8\xcf\xc0\x00\x00\x03\x01"
    b"\x01\x00\xc9\xfe\x92\xef\x00\x00\x00\x00IEND\xaeB`\x82"
)


@override_settings(BC_STORAGE_BACKEND="local")
class AttachmentContentViewTests(TestCase):

    @classmethod
    def setUpTestData(cls):
        cls.tenant = Tenant.objects.create(name="T", slug="t", status="ACTIVE")
        cls.user = User.objects.create_user(email="u@t.example.com", password="Pass1234!")
        cls.client_obj = Client.objects.create(
            tenant=cls.tenant, name="C", status="ACTIVE",
        )
        cls.eng = Engagement.objects.create(
            tenant=cls.tenant, name="E", client=cls.client_obj,
            created_by=cls.user, status="ACTIVE",
        )

        file_obj = SimpleUploadedFile("test.png", TINY_PNG, content_type="image/png")
        service = AttachmentUploadService()
        cls.att = service.upload_image(
            tenant=cls.tenant,
            tenant_id=str(cls.tenant.id),
            engagement=cls.eng,
            user=cls.user,
            file_obj=file_obj,
        )

    def test_valid_sig_with_tenant_returns_200(self):
        url = sign_attachment_url(self.att.pk, tenant_id=str(self.tenant.id))
        resp = self.client.get(url)
        self.assertEqual(resp.status_code, 200)

    def test_valid_sig_without_tenant_returns_200(self):
        """Backward compat: URLs without tid still work (no tenant filter)."""
        url = sign_attachment_url(self.att.pk)
        resp = self.client.get(url)
        self.assertEqual(resp.status_code, 200)

    def test_missing_sig_returns_404(self):
        resp = self.client.get(f"/api/attachments/{self.att.pk}/content/")
        self.assertEqual(resp.status_code, 404)

    def test_bad_sig_returns_404(self):
        resp = self.client.get(
            f"/api/attachments/{self.att.pk}/content/?sig=0000000000000000"
        )
        self.assertEqual(resp.status_code, 404)

    def test_valid_sig_nonexistent_id_returns_404(self):
        fake_id = uuid.uuid4()
        url = sign_attachment_url(fake_id)
        resp = self.client.get(url)
        self.assertEqual(resp.status_code, 404)

    def test_response_has_security_headers(self):
        url = sign_attachment_url(self.att.pk, tenant_id=str(self.tenant.id))
        resp = self.client.get(url)
        self.assertEqual(resp["X-Content-Type-Options"], "nosniff")
        self.assertIn("no-cache", resp["Cache-Control"])
        self.assertIn("Content-Disposition", resp)
