# Generated by Django 6.0.2 on 2026-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'key'], name='core_rateli_scope_7c207f_idx')],
                'unique_together': {('scope', 'key')},
            },
        ),
    ]
