"""
Audit trail gap tests — covers operations not tested in audit/tests.py:

- Auth events (signup, login success/failure, logout, tenant switch)
- Finding READ (sensitive read)
- Attachment CREATE (image upload) and READ (content download)
- Group management CUD + member add/remove
- Member management CUD + toggle-active
"""
import base64

from django.core.cache import cache
from django.core.files.uploadedfile import SimpleUploadedFile
from rest_framework.test import APITestCase

from accounts.models import User
from audit.models import AuditAction, AuditLog
from authorization.seed import seed_permissions, create_default_groups_for_tenant
from core.test_utils import login_as
from tenancy.models import Tenant, TenantMember, TenantRole


STRONG_PASSWORD = "Str0ngP@ss!99"

# Valid 1×1 red PNG (generated by Pillow, passes magic + decode validation).
TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMB"
    "AQDJ/pLvAAAAAElFTkSuQmCC"
)


# ---------------------------------------------------------------------------
# Helpers (same pattern as audit/tests.py)
# ---------------------------------------------------------------------------


def _create_user(email="gap@example.com", password=STRONG_PASSWORD, **kwargs):
    kwargs.setdefault("email_verified", True)
    return User.objects.create_user(email=email, password=password, **kwargs)


def _create_tenant(name="Gap Corp", slug="gap-corp", **kwargs):
    return Tenant.objects.create(name=name, slug=slug, **kwargs)


def _create_membership(user, tenant, role=TenantRole.OWNER, is_active=True):
    return TenantMember.objects.create(
        tenant=tenant, user=user, role=role, is_active=is_active,
    )


def _setup_tenant_with_groups():
    tenant = _create_tenant()
    seed_permissions()
    groups = create_default_groups_for_tenant(tenant)
    return tenant, groups




# ---------------------------------------------------------------------------
# 1. Auth audit tests
# ---------------------------------------------------------------------------


class AuthAuditTests(APITestCase):
    """Verify audit entries for signup, login, logout, tenant switch."""

    def setUp(self):
        cache.clear()
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="auth@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)
        login_as(self.client, self.user, self.tenant)
        AuditLog.objects.all().delete()

    def test_login_failed_creates_audit_entry(self):
        self.client.logout()
        resp = self.client.post("/api/auth/login/", {
            "email": "auth@gap.example.com",
            "password": "WrongPassword!1",
        }, format="json")
        self.assertIn(resp.status_code, [400, 401])

        log = AuditLog.objects.get(
            resource_type="auth", action=AuditAction.LOGIN_FAILED,
        )
        self.assertEqual(log.resource_repr, "Login failed: auth@gap.example.com")
        self.assertIsNone(log.actor)
        self.assertEqual(log.actor_email, "")

    def test_login_failed_returns_usable_error_message(self):
        """Wrong password response should contain the actual error, not
        a generic 'Validation error.' with a request ID."""
        resp = self.client.post("/api/auth/login/", {
            "email": "auth@gap.example.com",
            "password": "WrongPassword!1",
        }, format="json")
        data = resp.json()
        # The message field should carry the real error
        self.assertIn("Invalid email or password", data["message"])

    def test_login_failed_audit_visible_in_list_api(self):
        """Failed login audit entries should be visible when querying
        the audit list API for the same tenant."""
        # Trigger a failed login (no tenant header — pre-auth)
        self.client.post("/api/auth/login/", {
            "email": "auth@gap.example.com",
            "password": "WrongPassword!1",
        }, format="json")

        # Verify entry was written to DB
        self.assertTrue(
            AuditLog.objects.filter(action=AuditAction.LOGIN_FAILED).exists(),
            "Audit entry should exist in the database",
        )

        # Query the audit list API as admin
        resp = self.client.get(
            "/api/audit/",
        )
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        login_failed = [
            e for e in data["results"] if e["action"] == "login_failed"
        ]
        self.assertEqual(
            len(login_failed), 1,
            "Failed login audit entry should appear in the tenant audit list",
        )

    def test_login_success_creates_audit_entry(self):
        # Use a MEMBER (not OWNER) to avoid MFA gate blocking full login
        member_user = User.objects.create_user(
            email="loginok@gap.example.com", password=STRONG_PASSWORD,
            email_verified=True,
        )
        TenantMember.objects.create(
            tenant=self.tenant, user=member_user, role=TenantRole.MEMBER, is_active=True,
        )
        self.client.logout()
        resp = self.client.post("/api/auth/login/select-tenant/", {
            "email": "loginok@gap.example.com",
            "password": STRONG_PASSWORD,
            "tenant_id": str(self.tenant.id),
        }, format="json")
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(
            resource_type="auth", action=AuditAction.LOGIN_SUCCESS,
        )
        self.assertIn("loginok@gap.example.com", log.resource_repr)
        self.assertIn(self.tenant.name, log.resource_repr)
        self.assertEqual(log.tenant, self.tenant)

    def test_logout_creates_audit_entry(self):
        resp = self.client.post(
            "/api/auth/logout/",
            {},
            format="json",
        )
        self.assertEqual(resp.status_code, 204)

        log = AuditLog.objects.get(
            resource_type="auth", action=AuditAction.LOGOUT,
        )
        self.assertEqual(log.resource_repr, f"Logout: {self.user.email}")
        self.assertEqual(log.tenant, self.tenant)

    def test_switch_tenant_creates_audit_entry(self):
        # Create a second tenant + membership for the same user
        tenant2 = Tenant.objects.create(name="Second Corp", slug="second-corp")
        create_default_groups_for_tenant(tenant2)
        TenantMember.objects.create(
            tenant=tenant2, user=self.user, role=TenantRole.MEMBER,
        )
        AuditLog.objects.all().delete()

        resp = self.client.post(
            "/api/auth/switch-tenant/",
            {"tenant_id": str(tenant2.id)},
            format="json",
        )
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(
            resource_type="auth", action=AuditAction.TENANT_SWITCH,
        )
        self.assertEqual(log.resource_repr, f"Tenant switch: {tenant2.id}")


# ---------------------------------------------------------------------------
# 2. Finding READ audit
# ---------------------------------------------------------------------------


class FindingReadAuditTests(APITestCase):
    """Verify audit entry for retrieving a single finding (sensitive read)."""

    def setUp(self):
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="findread@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)
        login_as(self.client, self.user, self.tenant)

        from clients.models import Client
        from assets.models import Asset

        org = Client.objects.create(tenant=self.tenant, name="FindCo")
        self.asset = Asset.objects.create(
            tenant=self.tenant, client=org, name="webapp",
            asset_type="webapp",
        )

        # Create engagement via API (auto-creates Sow)
        resp = self.client.post(
            "/api/engagements/",
            {"name": "FindEng", "status": "active", "client_id": str(org.pk)},
            format="json",
        )
        self.assertEqual(resp.status_code, 201)
        self.eng_id = resp.json()["id"]

        # Add asset to scope
        self.client.post(
            f"/api/engagements/{self.eng_id}/scope/",
            {"asset_id": str(self.asset.pk)},
            format="json",
        )

        # Approve SoW so findings can be created
        self.client.patch(
            f"/api/engagements/{self.eng_id}/sow/",
            {"status": "approved"},
            format="json",
        )

        # Create finding
        resp = self.client.post(
            f"/api/engagements/{self.eng_id}/findings/",
            {"title": "XSS Gap", "severity": "high", "asset_id": str(self.asset.pk)},
            format="json",
        )
        self.assertEqual(resp.status_code, 201)
        self.finding_id = resp.json()["id"]

        AuditLog.objects.all().delete()

    def test_finding_retrieve_creates_read_audit(self):
        resp = self.client.get(
            f"/api/engagements/{self.eng_id}/findings/{self.finding_id}/",
        )
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(resource_type="finding", action=AuditAction.READ)
        self.assertEqual(log.resource_id, str(self.finding_id))
        self.assertEqual(log.resource_repr, "Finding: XSS Gap")


# ---------------------------------------------------------------------------
# 3. Attachment upload audit
# ---------------------------------------------------------------------------


class AttachmentUploadAuditTests(APITestCase):
    """Verify audit entry for image upload."""

    def setUp(self):
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="upload@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)
        login_as(self.client, self.user, self.tenant)

        from clients.models import Client

        org = Client.objects.create(tenant=self.tenant, name="UploadCo")

        resp = self.client.post(
            "/api/engagements/",
            {"name": "UploadEng", "status": "active", "client_id": str(org.pk)},
            format="json",
        )
        self.assertEqual(resp.status_code, 201)
        self.eng_id = resp.json()["id"]

        AuditLog.objects.all().delete()

    def test_image_upload_creates_audit_entry(self):
        img = SimpleUploadedFile("test.png", TINY_PNG, content_type="image/png")
        resp = self.client.post(
            f"/api/engagements/{self.eng_id}/attachments/images/",
            {"file": img},
            format="multipart",
        )
        self.assertEqual(resp.status_code, 201)

        log = AuditLog.objects.get(
            resource_type="attachment", action=AuditAction.CREATE,
        )
        self.assertEqual(log.resource_repr, "Image: test.png")
        self.assertTrue(log.resource_id)  # non-empty UUID


# ---------------------------------------------------------------------------
# 4. Attachment READ audit (anonymous)
# ---------------------------------------------------------------------------


class AttachmentReadAuditTests(APITestCase):
    """Verify audit entry for anonymous attachment content download."""

    def setUp(self):
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="attread@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)

        from engagements.models import Engagement
        from clients.models import Client
        from evidence.services.attachment_upload import AttachmentUploadService

        org = Client.objects.create(tenant=self.tenant, name="AttReadCo")
        self.eng = Engagement.objects.create(
            tenant=self.tenant, name="AttReadEng", status="active",
            client=org, created_by=self.user,
        )

        file_obj = SimpleUploadedFile("read.png", TINY_PNG, content_type="image/png")
        service = AttachmentUploadService()
        self.att = service.upload_image(
            tenant=self.tenant,
            tenant_id=str(self.tenant.id),
            engagement=self.eng,
            user=self.user,
            file_obj=file_obj,
        )

        AuditLog.objects.all().delete()

    def test_attachment_read_creates_audit_anonymous(self):
        from evidence.signing import sign_attachment_url
        url = sign_attachment_url(self.att.pk)
        resp = self.client.get(url)
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(
            resource_type="attachment", action=AuditAction.READ,
        )
        self.assertEqual(log.resource_id, str(self.att.pk))
        self.assertEqual(log.resource_repr, "Attachment: read.png")
        self.assertIsNone(log.actor)
        self.assertEqual(log.actor_email, "")


# ---------------------------------------------------------------------------
# 5. Group management audit
# ---------------------------------------------------------------------------


class GroupManagementAuditTests(APITestCase):
    """Verify audit entries for group CRUD and member add/remove."""

    def setUp(self):
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="grpmgmt@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)
        login_as(self.client, self.user, self.tenant)
        AuditLog.objects.all().delete()

    def _api(self, method, url, data=None):
        fn = getattr(self.client, method)
        kwargs = {}
        if data is not None:
            return fn(url, data, format="json", **kwargs)
        return fn(url, **kwargs)

    def test_group_create_creates_audit_entry(self):
        resp = self._api("post", "/api/authorization/groups/", {
            "name": "Pentesters",
            "permission_ids": [],
        })
        self.assertEqual(resp.status_code, 201)

        log = AuditLog.objects.get(resource_type="group", action=AuditAction.CREATE)
        self.assertEqual(log.resource_repr, "Group: Pentesters")
        self.assertIsNone(log.before)
        self.assertIsNotNone(log.after)

    def test_group_update_creates_audit_entry(self):
        # Create a custom group first
        resp = self._api("post", "/api/authorization/groups/", {
            "name": "Updatable",
            "permission_ids": [],
        })
        gid = resp.json()["id"]
        AuditLog.objects.all().delete()

        resp = self._api("patch", f"/api/authorization/groups/{gid}/", {
            "name": "Renamed",
        })
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(resource_type="group", action=AuditAction.UPDATE)
        self.assertIsNotNone(log.before)
        self.assertIsNotNone(log.after)
        self.assertIsNotNone(log.diff)
        self.assertIn("name", log.diff)

    def test_group_delete_creates_audit_entry(self):
        resp = self._api("post", "/api/authorization/groups/", {
            "name": "Doomed Group",
            "permission_ids": [],
        })
        gid = resp.json()["id"]
        AuditLog.objects.all().delete()

        resp = self._api("delete", f"/api/authorization/groups/{gid}/")
        self.assertEqual(resp.status_code, 204)

        log = AuditLog.objects.get(resource_type="group", action=AuditAction.DELETE)
        self.assertIsNotNone(log.before)
        self.assertIsNone(log.after)
        self.assertEqual(log.resource_repr, "Group: Doomed Group")

    def test_group_member_add_creates_audit_entry(self):
        # Create a custom group
        resp = self._api("post", "/api/authorization/groups/", {
            "name": "AddTest",
            "permission_ids": [],
        })
        gid = resp.json()["id"]

        # Create a second user to add
        user2 = _create_user(email="target@gap.example.com")
        member2 = _create_membership(
            user2, self.tenant, role=TenantRole.MEMBER,
        )
        AuditLog.objects.all().delete()

        resp = self._api(
            "post",
            f"/api/authorization/groups/{gid}/members/",
            {"member_id": str(member2.pk)},
        )
        self.assertEqual(resp.status_code, 201)

        log = AuditLog.objects.get(resource_type="group", action=AuditAction.UPDATE)
        self.assertIn("Added member", log.resource_repr)
        self.assertIn("target@gap.example.com", log.resource_repr)

    def test_group_member_remove_creates_audit_entry(self):
        # Create a custom group
        resp = self._api("post", "/api/authorization/groups/", {
            "name": "RemoveTest",
            "permission_ids": [],
        })
        gid = resp.json()["id"]

        # Create a second user and add to group
        user2 = _create_user(email="removable@gap.example.com")
        member2 = _create_membership(
            user2, self.tenant, role=TenantRole.MEMBER,
        )
        self._api(
            "post",
            f"/api/authorization/groups/{gid}/members/",
            {"member_id": str(member2.pk)},
        )
        AuditLog.objects.all().delete()

        resp = self._api(
            "delete",
            f"/api/authorization/groups/{gid}/members/{member2.pk}/",
        )
        self.assertEqual(resp.status_code, 204)

        log = AuditLog.objects.get(resource_type="group", action=AuditAction.UPDATE)
        self.assertIn("Removed member", log.resource_repr)
        self.assertIn("removable@gap.example.com", log.resource_repr)

    def test_default_group_update_rejected_no_audit(self):
        # Pick a default group
        from authorization.models import TenantGroup
        default_group = TenantGroup.objects.filter(
            tenant=self.tenant, is_default=True,
        ).first()
        self.assertIsNotNone(default_group)

        resp = self._api("patch", f"/api/authorization/groups/{default_group.pk}/", {
            "name": "Hacked",
        })
        self.assertEqual(resp.status_code, 403)
        self.assertEqual(
            AuditLog.objects.filter(resource_type="group").count(), 0,
        )


# ---------------------------------------------------------------------------
# 6. Member management audit
# ---------------------------------------------------------------------------


class MemberManagementAuditTests(APITestCase):
    """Verify audit entries for member CRUD and toggle-active."""

    def setUp(self):
        self.tenant, self.groups = _setup_tenant_with_groups()
        self.user = _create_user(email="membmgmt@gap.example.com")
        self.member = _create_membership(self.user, self.tenant)
        login_as(self.client, self.user, self.tenant)
        AuditLog.objects.all().delete()

    def _api(self, method, url, data=None):
        fn = getattr(self.client, method)
        kwargs = {}
        if data is not None:
            return fn(url, data, format="json", **kwargs)
        return fn(url, **kwargs)

    def test_member_create_creates_audit_entry(self):
        resp = self._api("post", "/api/authorization/members/", {
            "email": "newmember@gap.example.com",
            "first_name": "New",
            "last_name": "Member",
            "password": STRONG_PASSWORD,
            "password_confirm": STRONG_PASSWORD,
            "group_ids": [],
        })
        self.assertEqual(resp.status_code, 201)

        log = AuditLog.objects.get(resource_type="member", action=AuditAction.CREATE)
        self.assertEqual(log.resource_repr, "Member: newmember@gap.example.com")
        self.assertIsNone(log.before)
        self.assertIsNotNone(log.after)

    def test_member_update_creates_audit_entry(self):
        # Create a target member first
        resp = self._api("post", "/api/authorization/members/", {
            "email": "editable@gap.example.com",
            "first_name": "Edit",
            "last_name": "Me",
            "password": STRONG_PASSWORD,
            "password_confirm": STRONG_PASSWORD,
            "group_ids": [],
        })
        mid = resp.json()["id"]
        AuditLog.objects.all().delete()

        resp = self._api("patch", f"/api/authorization/members/{mid}/", {
            "first_name": "Edited",
        })
        self.assertEqual(resp.status_code, 200)

        log = AuditLog.objects.get(resource_type="member", action=AuditAction.UPDATE)
        self.assertIsNotNone(log.before)
        self.assertIsNotNone(log.after)
        self.assertIsNotNone(log.diff)

    def test_member_delete_creates_audit_entry(self):
        resp = self._api("post", "/api/authorization/members/", {
            "email": "deletable@gap.example.com",
            "first_name": "Del",
            "last_name": "Me",
            "password": STRONG_PASSWORD,
            "password_confirm": STRONG_PASSWORD,
            "group_ids": [],
        })
        mid = resp.json()["id"]
        AuditLog.objects.all().delete()

        resp = self._api("delete", f"/api/authorization/members/{mid}/")
        self.assertEqual(resp.status_code, 204)

        log = AuditLog.objects.get(resource_type="member", action=AuditAction.DELETE)
        self.assertIsNotNone(log.before)
        self.assertIsNone(log.after)
        self.assertEqual(log.resource_repr, "Member: deletable@gap.example.com")

    def test_member_toggle_active_creates_audit_entry(self):
        resp = self._api("post", "/api/authorization/members/", {
            "email": "lockable@gap.example.com",
            "first_name": "Lock",
            "last_name": "Me",
            "password": STRONG_PASSWORD,
            "password_confirm": STRONG_PASSWORD,
            "group_ids": [],
        })
        mid = resp.json()["id"]
        AuditLog.objects.all().delete()

        resp = self._api("post", f"/api/authorization/members/{mid}/toggle-active/")
        self.assertEqual(resp.status_code, 200)
        self.assertFalse(resp.json()["is_active"])

        log = AuditLog.objects.get(resource_type="member", action=AuditAction.UPDATE)
        self.assertIn("locked", log.resource_repr)
        self.assertEqual(log.before, {"is_active": True})
        self.assertEqual(log.after, {"is_active": False})

    def test_owner_delete_rejected_no_audit(self):
        resp = self._api("delete", f"/api/authorization/members/{self.member.pk}/")
        self.assertEqual(resp.status_code, 403)
        self.assertEqual(
            AuditLog.objects.filter(resource_type="member").count(), 0,
        )
